services:
  traefik:
    image: traefik:3.3.2
    restart: unless-stopped
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_PORT:-443}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik-config.d:/etc/traefik/traefik-config.d
      - ./certs:/etc/traefik/certs
    networks:
      - traefik

networks:
  traefik:
    external: true
